MyWebApp/Models/Song.cs
using System.ComponentModel.DataAnnotations;

namespace MyWebApp.Models;

    public class Song
    {
        [Required]
        public int songId { get; set; }
        public string? title { get; set; }
        public string? artist { get; set; }
        public DateTime dateAdded { get; set; }
        //public DateTime dateFavorited { get; set; }
        //public DateTime dateDeleted
        //public static int totalNumSongs =0;

        public bool isFave= false;


       /* public Song()
        {
            songId = -1;
            title = "";
            artist = "";
            dateAdded = new DateTime(1970,1,1);
            //totalNumSongs++;
        }*/

         public Song(int sngId, string ttl, string rtst, DateTime dtAdded)
        {
            songId = sngId;
            title = ttl;
            artist = rtst;
            dateAdded = dtAdded; 
            //totalNumSongs++;
        }

    }

MyWebApp/Pages/AddSong.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyWebApp.Models;
using MyWebApp.Services;

namespace MyWebApp.Pages
{
    public class AddSongModel : PageModel
    {
        [BindProperty]
        public string? newTitle {get;set;} = "no title given";


        [BindProperty]
        public string? newArtist {get;set;} = "no artist given";

        public void OnGet()
        {
        }

        public RedirectResult OnPostAddNewSong(string newTitle,string newArtist)
        {
            SongService.AddNewSong(newTitle, newArtist);
            return Redirect("/Song");
        }












    }
}

MyWebApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyWebApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


MyWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyWebApp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

MyWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyWebApp.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


MyWebApp/Pages/Song.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyWebApp.Models;
using MyWebApp.Services;

namespace MyWebApp.Pages
{
    public class SongModel : PageModel
    {
        public List<Song> allSongs = new();
        [BindProperty]
        public int songIdToDelete {get; set;} = new();

        [BindProperty]
        public int songIdToFav {get; set;} = new();
        public void OnGet()
        {
            allSongs = SongService.GetAll();
        }

        public IActionResult OnPost()
        {
            return RedirectToAction("Get");
        }

        public IActionResult OnPostDeleteButton(int songIdToDelete)
        {
            SongService.DeleteSong(songIdToDelete);
            return RedirectToAction("Get");
        }

        public IActionResult OnPostFavButton(int songIdToFav)
        {
            SongService.FavoriteSong(songIdToFav);
            return Redirect("/Song");
        }


    }
}

MyWebApp/Pages/AddSong.cshtml
@page
@model MyWebApp.Pages.AddSongModel
@{
    ViewData["Title"] = "Add a Song";
}
<head>
    <style>
        h1{
            text-align: center;
            font-family: impact;
            color: pink;
            border-style: groove;
            border-width: 15pt;
            border-color: mistyrose;
            margin-left: 35%;
            margin-right: 35%;
            height: 120px;
            padding-top: 15px;
            }
        input {
            width: 70%;   
            }
        div.songform {
            margin-left:25%;
        }
        
        .submitButton {
            width:70%;
            height:60px;
           
        }
    </style>
</head>
<h1> Add a Song</h1>
<form method="post" asp-page-handler="AddNewSong">
    <p>
    <div class="songform">
    <label asp-for="newTitle">Title: </label><p></p>
    <input type="text" asp-for="newTitle" id="_newTitle" name="newTitle"></div><p></p>
    <div class="songform"><label asp-for="newArtist">Artist: </label><p></p>
    <input type="text" asp-for="newArtist" id="_newArtist" name = "newArtist"></div><p></p>
    <div class="songform"><input class="submitButton" type="submit"></div>
    </p>
</form>

MyWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4"> Houndstoothify </h1>
    <p> Helping you keep track of your favorite tracks!</p>
</div>

MyWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Song">My Songs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyWebApp/Pages/Song.cshtml
@page
@using MyWebApp.Models
@using MyWebApp.Services
@model MyWebApp.Pages.SongModel 
@{ 
    ViewData["Title"] = "My Songs"; 
}
<head>
    <style>
        button{
            font-size: 11pt;
        }
        table{
            width: 100%;
            
        }    
        th{
            text-align: center;
            font-size: 16pt;
            background-color:pink ;

        }
        td{
            text-align: center;
            font-size: 14pt;
        }
        h1{
            text-align: center;
            font-family: impact;
        }
        tr:nth-child(even) {
            background-color: mistyrose;
        }
        tr:nth-child(odd) {
            background-color: snow;
        }
    </style>
</head>
<h1>My Songs</h1>
<table>                  
    <thead>
        <th scope="col">Song ID</th>
        <th scope="col" style= "margin-left =10px">Title</th>
        <th scope="col">Artist</th>
        <th scope="col">Date Added</th>
        <th scope="col">Faved?</th>
        <th scope="col"> 
            <form action = "/AddSong"> 
                <button> ➕ Add song</button> 
            </form> 
        </th> 

    </thead>
    @foreach (var aSong in Model.allSongs)
    {
        <tr>
            <td> @aSong.songId </td>
            <td> @aSong.title</td>
            <td> @aSong.artist</td>
            <td> @aSong.dateAdded</td>
            @if (aSong.isFave == true) 
            { 
               <td> 
                    <form method = "post" asp-page-handler="FavButton" asp-route-songIdToFav="@aSong.songId">
                        <button> &hearts; </button> 
                    </form>  
                </td>
            } 
            else 
            { 
                <td> 
                    <form method = "post" asp-page-handler="FavButton" asp-route-songIdToFav="@aSong.songId"> 
                        <button> ♡ </button>
                    </form> 
                </td>
            }
            <td> 
                <form method = "post" asp-page-handler="DeleteButton" asp-route-songIdToDelete="@aSong.songId"> 
                    <button>Delete song</button> 
                </form> 
            </td>


        </tr>
    }




</table>
